from __future__ import annotations

from pathlib import Path

# -----------------
# Paths
# -----------------
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Source CSV (CNN-friendly long format generated by notebooks/Analysis.ipynb)
CNN_LONG_CSV_PATH = PROJECT_ROOT / "data" / "raw" / "leak_dataset_long.csv"

SCENARIO_ID_COL = "scenario_id"
HOUR_COL = "hour"

# Targets
TARGET_COLUMNS = ["leak_x", "leak_y", "leak_size_lpm"]

# Sensor column detection
# In the regenerated long CSV, sensor columns are the node base names (no _Hour suffix).
SENSOR_NODE_PREFIXES = ["NODEADD", "NODE", "HOUSE_EPN"]

# Expected shape
NUM_HOURS = 24
# NUM_SENSORS is inferred from detected sensor columns; kept here for documentation.
NUM_SENSORS = 21
INPUT_SHAPE = (24, 21, 1)

# -----------------
# Splits (shared across runs)
# -----------------
SPLITS_DIR = PROJECT_ROOT / "data" / "splits" / "cnn_2d"
SPLIT_IDS_DIR = SPLITS_DIR / "shared_ids"

TRAIN_FRACTION = 0.7
VAL_FRACTION = 0.1
TEST_FRACTION = 0.2
RANDOM_STATE = 42

# -----------------
# Preprocessing
# -----------------
NORMALIZE_PRESSURES = True
PRESSURE_NORMALIZATION_MODE = "per_sensor"  # currently supported: per_sensor
NORMALIZE_TARGETS = True

CNN2D_READY_NPZ_PATH = PROJECT_ROOT / "data" / "processed" / "cnn2d_ready.npz"
CNN2D_SCALERS_PATH = PROJECT_ROOT / "data" / "processed" / "cnn2d_ready__scalers.joblib"
CNN2D_META_PATH = PROJECT_ROOT / "data" / "processed" / "cnn2d_ready__meta.json"

REBUILD_PROCESSED_ON_RUN = False
REBUILD_SHARED_SPLIT_IDS_ON_RUN = False

# -----------------
# Outputs (per-run)
# -----------------
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

# Increment this integer when you want a fresh set of output artifacts.
RUN_NUM = 1
OUTPUTS_RUN_DIR = OUTPUTS_DIR / f"run_{int(RUN_NUM)}"

MODEL_DIR = OUTPUTS_RUN_DIR / "models" / "cnn_2d" / "baseline"
MODEL_PATH = MODEL_DIR / "cnn2d_baseline.pt"

METRICS_DIR = OUTPUTS_RUN_DIR / "metrics" / "cnn_2d" / "baseline"
PREDICTIONS_DIR = OUTPUTS_RUN_DIR / "predictions" / "cnn_2d" / "baseline"
PLOTS_DIR = OUTPUTS_RUN_DIR / "plots" / "cnn_2d" / "baseline"

# -----------------
# Model architecture
# -----------------
CONV_FILTERS = [32, 64, 128]
KERNEL_SIZES = [(3, 3), (3, 3), (3, 3)]
POOL_SIZES = [(2, 2), (2, 2)]
DROPOUT_RATES = [0.2, 0.25, 0.3]
DENSE_UNITS = [128, 64]
USE_GLOBAL_AVG_POOL = True
USE_BATCH_NORM = True

# -----------------
# Training
# -----------------
BATCH_SIZE = 32
EPOCHS = 100
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4

LOSS = "huber"  # currently supported: huber
HUBER_DELTA = 1.0

EARLY_STOPPING_PATIENCE = 12
REDUCE_LR_PATIENCE = 5
REDUCE_LR_FACTOR = 0.5
MIN_LR = 1e-5

TORCH_SEED = 42
