from __future__ import annotations

from pathlib import Path

# -----------------
# Paths
# -----------------
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Input CSV (CNN-friendly long format generated by notebooks/Analysis.ipynb)
# Expected columns: scenario_id, hour, targets, and one column per sensor node (e.g. NODE_3005)
CNN_LONG_CSV_PATH = PROJECT_ROOT / "data" / "raw" / "leak_dataset_long.csv"

SCENARIO_ID_COL = "scenario_id"
HOUR_COL = "hour"

# Targets
TARGET_COLUMNS = ["leak_x", "leak_y", "leak_size_lpm"]

# Sensor column detection
# In the regenerated long CSV, sensor columns are the node base names (no _Hour suffix).
SENSOR_NODE_PREFIXES = ["NODEADD", "NODE", "HOUSE_EPN"]

# Expected shape
NUM_HOURS = 24

# -----------------
# Splits (shared across runs)
# -----------------
SPLITS_DIR = PROJECT_ROOT / "data" / "splits" / "cnn"
SPLIT_IDS_DIR = SPLITS_DIR / "shared_ids"

TRAIN_FRACTION = 0.7
VAL_FRACTION = 0.1
TEST_FRACTION = 0.2
RANDOM_STATE = 42

# -----------------
# Preprocessing
# -----------------
NORMALIZE_PRESSURES = True
NORMALIZE_TARGETS = True

# Save processed tensors as NPZ (reused across runs)
CNN_READY_NPZ_PATH = PROJECT_ROOT / "data" / "processed" / "cnn_ready.npz"
CNN_SCALERS_PATH = PROJECT_ROOT / "data" / "processed" / "cnn_ready__scalers.joblib"
CNN_META_PATH = PROJECT_ROOT / "data" / "processed" / "cnn_ready__meta.json"

REBUILD_PROCESSED_ON_RUN = False
REBUILD_SHARED_SPLIT_IDS_ON_RUN = False

# -----------------
# Outputs (per-run)
# -----------------
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

# Increment this integer when you want a fresh set of output artifacts.
RUN_NUM = 1
OUTPUTS_RUN_DIR = OUTPUTS_DIR / f"run_{int(RUN_NUM)}"

# Default artifact paths (used by evaluate/predict)
MODEL_DIR = OUTPUTS_RUN_DIR / "models" / "cnn" / "baseline"
MODEL_PATH = MODEL_DIR / "cnn_baseline.pt"

METRICS_DIR = OUTPUTS_RUN_DIR / "metrics" / "cnn" / "baseline"
PREDICTIONS_DIR = OUTPUTS_RUN_DIR / "predictions" / "cnn" / "baseline"
PLOTS_DIR = OUTPUTS_RUN_DIR / "plots" / "cnn" / "baseline"

# -----------------
# Model architecture
# -----------------
CONV_FILTERS = [32, 64, 128]
KERNEL_SIZE = 3
POOL_SIZE = 2
DROPOUT_RATES = [0.2, 0.2, 0.3]
DENSE_UNITS = [128, 64]
USE_GLOBAL_AVG_POOL = True

# -----------------
# Training
# -----------------
BATCH_SIZE = 32
EPOCHS = 100
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4

LOSS = "huber"  # currently supported: huber
HUBER_DELTA = 1.0

EARLY_STOPPING_PATIENCE = 12
REDUCE_LR_PATIENCE = 5
REDUCE_LR_FACTOR = 0.5
MIN_LR = 1e-5

# Reproducibility
TORCH_SEED = 42
